name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  Linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Build
      #   run: |
      #     cmake . -B build
      #     cmake --build build

      # - name: Run tests
      #   run:  build/tests/Debug/Tests

  Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          cmake . -B build
          cmake --build build

      - name: Run tests
        run: build\tests\Debug\Tests.exe
